### ISSUE TITLE
§1.1 Servo programmeren

### ISSUE THREAD

**Issue by OnurcanCekem** [EHammer98/DigitalPlastic#35]
Zie #2 (User story)

- [x] Onderzoek structs, kijk wat een struct is en hoe je er één maakt.

- [x] Maak een struct dat 3 integers accepteert (x,y,z).

- [x] Onderzoek hoe je de servo normaal aaanstuurt.

- [x] Stuur de servo aan via de struct.

- [x] Herschrijf de code naar een functie met de volgende prototype: void stuur_servo_aan (struct setpoint_servowaarde).

**Comment by EHammer98** [comment]
170 graden max & 60 graden min.
Volgens huidige hardware afstelling
